version: "2.19.1"
services:
  frontend:
    build: ./
    container_name: fitapp-react_c
    ports:
      - '3000:3000'
    volumes:
      - ./fit-app:/app
      - /app/node_modules
  db:
    image: mysql:8.0
    cap_add:
        - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: fitdb
      MYSQL_ROOT_PASSWORD: 5oT4^82O8#90
    ports:
      - "3306:3306"    
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
